name: Test

on:
  push:
    paths:
      - test/**

jobs:
  test:
    runs-on: ubuntu-20.04
    
    steps:
      - uses: actions/checkout@v2
      - name: Check test makefile
        run: |
          make -C test
